### ISSUE TITLE
React router url suffix added on every click

### ISSUE THREAD

**Issue by bartolomej** [jakic12/its-client#1]
Routing path suffix keeps adding to route after multiple clicks on routing button.

#### EXPECTED BEHAVIOUR
`http://localhost:3000/course/12314124`

#### ACTUAL BEHAVIOUR
`http://localhost:3000/dash/course/course/course/course/course/course/12314124`

**Comment by jakic12** [comment]
fixed in 161a885733a6f164a9dda96c6783c5640db89a81
